### PR TITLE
Mise à jour et nouvelle traduction

### PR DESCRIPTION
**Pull request by joniroutypo3**
Bonjour,
J'ai traduit de nouvelles sections : 

- /ListModule/
- /FileModule/
- /ExtensionManager/
- /UserManagement/

Et fait une mise à jour de la syntaxe de la table des matière
/Index.rst

### CODE REVIEW

**Comment by fsuter** [comment]
Super, merci pour tes efforts!

**Comment by marble** [comment]
I hope you saw https://docs.typo3.org/typo3cms/GettingStartedTutorial/fr_FR/ 
It should appear in the "Related Links" section of the manual at the lower left, but it doesn't. I will look at the script that's generating those links. Thank you for the translation :-))

**Comment by fsuter** [comment]
Martin, have you noticed that the left-hand menu is in English? Isn't that weird?

**Comment by joniroutypo3** [comment]
Hello Martin,

Thank you for your help.

Jonathan

**Comment by joniroutypo3** [comment]
I didn’t saw the link.

**Comment by joniroutypo3** [comment]
Martin, the other links (In on file:*) goes to the english version.
I may have made a mistake in files structure.
Can you tell me if i have to correct some structure file.

**Comment by joniroutypo3** [comment]
Martin,
The « previous/next » links in the bottom of each page are missing.
If i have to correct something i’ll do.

Jonathan

**Comment by marble** [comment]
Ok, I'm very happy that all of this is happening. It's a wonderful test case. I've attended the ServerTeamSprint at the recent weekend. It was very inspiring and I can already smell a brand new server with a Debian 8.4 coming up for the Documentation. I'll work on this ASAP. And that's the moment where this tutorial will be the test case for rendering multi-language projects. It may take a moment until I get there. But be asured that I'll doing and then I'll come back with feedback or questions. Have a nice easter ("Osterfest"). And big eggs of course :-))

**Comment by joniroutypo3** [comment]
Thank you Martin for your answer and all your work.

Have a nice easter too.

Jonathan

**Pull request merged**
