### PR TITLE
Update SiteRecords page

### PR DESCRIPTION
**Pull request by runepiper**
I updated the SiteRecords page according to #222.

Is it possible to add the `hacktoberfest-accepted` label?

### CODE REVIEW

**Review by brotkrueml — COMMENTED** [review]
As the changed image is a screenshot that is automatically generated, it would be overridden the next time the screenshots are generated.

@linawolf Can you have a look here?

**Comment by runepiper** [comment]
Oh my bad, sorry.

**Comment by linawolf** [comment]
> As the changed image is a screenshot that is automatically generated, it would be overridden the next time the screenshots are generated.

While this is true, once we have the screenshots for v12 up and running this screenshot will then be replaced with a new one automatically. So I see no harm in this. Also - for now - all screenshots changed beyond a certain threshhold are manually reviewed before we apply the changes.

Texts should be checked by @tomwarwick

**Comment by linawolf** [comment]
@tomwarwick could you please review the text changes in this PR?

**Pull request merged**
