### PR TITLE
Revert "[TASK] Switch the version information to the bottom (#212)"

### PR DESCRIPTION
**Pull request by alexander-nitsche**
Changes to the documentation structure should be handled by

1) discussing them in the documentation team channel
2) composing a new standard in the related documentation pages
3) applying the new standard to all official manuals
4) republishing the new standard

### CODE REVIEW

**Review by linawolf — CHANGES_REQUESTED** [review]
This is not a breaking of the standard, it is simply a change of order.

**Comment by alexander-nitsche** [comment]
The order is part of the structure and mentioned as well in theory in the documentation standard, the ready-for-use templates and the typo3.org article, as well as lived up to in the hundreds of revised manuals.

**Comment by linawolf** [comment]
I opened a discussion about this: https://decisions.typo3.org/t/layout-of-the-start-page-of-a-manual/773

**Comment by alexander-nitsche** [comment]
Right. Now, please approve this PR.

**Pull request merged**
