### PR TITLE
[TASK] Recommend composer req ...:@dev for local composer path repos

### PR DESCRIPTION
**Pull request by jonaseberle**

### CODE REVIEW

**Comment by mbrodala** [comment]
Personally I see the latter as disadvantage. If you create a feature branch and e.g. install a new 3rd party package, Composer inevitably updates `dev-<default-branch>` to `dev-<feature-branch>` in the course of the package installation.

If you later merge this branch, you end up with `dev-<feature-branch>` references in your `composer.lock` in your default branch. From time to time I see installation issues due to that. You need another lock file update in your default branch afterwards to fix this. Unfortunately I didn't have time to create a minimal reproducible repo yet.

(We **do** use `@dev` currently since there are no better options ATM.)

**Comment by jonaseberle** [comment]
I agree that having `dev-<branch when composer.lock was rewritten>` looks cumbersome.
But I haven't had any actual problems with it. I have the feeling that composer ignores it when resolving packages from local path repos but can't prove it.

**Review by linawolf — APPROVED** [review]
I think it is current best practise, so we should merge it like that. What do you think @mbrodala ?

**Comment by linawolf** [comment]
cannot be backported automatically to 10.4

**Pull request merged**
